# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'PersonalSpotify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PersonalSpotify
    pod 'Alamofire', '~> 4.4'

  target 'PersonalSpotifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PersonalSpotifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
